name=input ("what is your name :")
age = input("what is your age:")
place=input("what is your residence:")
dob =input("enter your date of birth:")
print("how are you " + name + "  Age: "+ age + "residence:"+ place +"dob:" +dob)
print("hello"+name)
height=float(input("what your height:"))
print("you are"+ str(height) + "cm")
print(" you are" + str(height/2.54)+ "inchestall")
weight=float(input("what is your weight:"))
print("you are" + str(weight)+ "kg" )
print("how are you")